parameters:
  toolchain: stable
  threads: 1

jobs:
- job: ${{ format('test_rust_{0}', parameters.toolchain) }}
  displayName: ${{ format('Rust ({0})', parameters.toolchain) }}
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: step-install-rust.yml
    parameters:
      toolchain: ${{ parameters.toolchain }}

  - script: cargo test --all -- --test-threads ${{ parameters.threads }}
    displayName: Run tests
