parameters:
  name: test_rust_stable
  label: Rust (stable)
  toolchain: stable
  threads: 1

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.label }}
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: step-install-rust.yml
    parameters:
      toolchain: ${{ parameters.toolchain }}

  - script: cargo test --all -- --test-threads ${{ parameters.threads }}
    displayName: Run tests
