parameters:
  toolchain: stable

stages:
- template: stage-lint.yml
  parameters:
    toolchain: ${{ parameters.toolchain }}

- template: stage-test.yml
  parameters:
    toolchain: ${{ parameters.toolchain }}
